// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrctcfvhzzkmlkexwkdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyY3RjZnZoenprbWxrZXh3a2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTUzNTUsImV4cCI6MjA3NDIzMTM1NX0.S9oJBKXJ7jxsd1a94YGoNErBFfTXCI47J_y4eAAqYJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});